
export const products = [{
    img: 'images/products/f1.jpg',
    brand: 'Adidas',
    productName: 'Cartoon T-Shirt',
    stars: 5,
    price: 78,
},
{
    img: 'images/products/f2.jpg',
    brand: 'Adidas',
    productName: 'Exotic T-Shirt',
    stars: 4,
    price: 59,
},
{
    img: 'images/products/f3.jpg',
    brand: 'CK',
    productName: 'Cartoon T-Shirt',
    stars: 5,
    price: 99,
},
{
    img: 'images/products/f4.jpg',
    brand: 'Nike',
    productName: 'Cartoon T-Shirt',
    stars: 4.5,
    price: 78,
},
{
    img: 'images/products/f5.jpg',
    brand: 'EA7',
    productName: 'Cartoon T-Shirt',
    stars: 4,
    price: 119,
},
{
    img: 'images/products/f6.jpg',
    brand: 'Gucci',
    productName: 'Cartoon T-Shirt',
    stars: 5,
    price: 199,
},
{
    img: 'images/products/f7.jpg',
    brand: 'Tex',
    productName: 'Pants with Flowers',
    stars: 3,
    price: 39,
},
{
    img: 'images/products/f8.jpg',
    brand: 'Puma',
    productName: 'Blouse',
    stars: 4.5,
    price: 109.99,
},
{
    img: 'images/products/n1.jpg',
    brand: 'Tommy',
    productName: 'Light Shirt',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},
{
    img: 'images/products/n2.jpg',
    brand: 'Tommy',
    productName: 'Dark Shirt',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},
{
    img: 'images/products/n3.jpg',
    brand: 'Tommy',
    productName: 'White Shirt',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},
{
    img: 'images/products/n4.jpg',
    brand: 'Tommy',
    productName: 'T-Shirt',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},
{
    img: 'images/products/n5.jpg',
    brand: 'Tommy',
    productName: 'Blue Shirt',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},
{
    img: 'images/products/n6.jpg',
    brand: 'Tommy',
    productName: 'Short Pants',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},
{
    img: 'images/products/n7.jpg',
    brand: 'Tommy',
    productName: 'Ginger Shirt',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},
{
    img: 'images/products/n8.jpg',
    brand: 'Tommy',
    productName: 'Black Shirt',
    stars: 3.5,
    price: 59,
    newArrivals: true,
},

]